@echo off
title PicZip
color 0a
echo Loading...
ping localhost -n 1 >nul
echo ................................................................................
echo ................................................................................
echo ................................................................................
echo .............................Made by Skrimbo_Jones.................................
echo ................................................................................
echo ................................................................................
echo ................................................................................
ping localhost -n 3 >nul
cls
echo Enter the file type of the currently loaded picture (EX: jpg, png, etc.):
set /p type=
echo Type the name of the newly created picture:
set /p name= 
cd/
cd PicZip-main
copy /b Picture.%type% + x.zip %name%.%type%
cls
echo All done! Check the folder "PicZip-main" and your picture will be in there.
pause
